name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: setting Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Instalar dependencias
        run: npm install

      - name: Run test
        run: npm run test
      
      - name: Build page
        run: npm run build

        ## This step is optional and can be used to generate a summary of the build process.
      - name: step summary example
        run: echo "Build completed successfully!" >> $GITHUB_STEP_SUMMARY

  notification:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Notify
        run: |
          echo "Build completed successfully!"
          echo "You can now deploy your application."